stages:
  - build
  - baseline


build-jiva:
   stage: build
   image: harshvkarn/dind:v6
   before_script:
     - export COMMIT=${CI_COMMIT_SHA:0:8}
   script: 
    - echo "Building-Jiva"
    - echo $COMMIT

baseline-image:
  only:
    - commit
  stage: baseline
  image: atulabhi/kops:v8
  script:
    - pwd
    - chmod 775 commit
    - ./commit
    - curl -X POST -F token=db44b8e26ce8ef4dc272679d007cad -F ref=master https://gitlab.openebs.ci/api/v4/projects/7/trigger/pipeline
    - curl -X POST -F token=3ac51c4e64d286c1ed45f23ad72a2c -F ref=master https://gitlab.openebs.ci/api/v4/projects/9/trigger/pipeline

  #  - git add .
  #  - git commit -m "updated baseline jiva"
  #  - git push 'https://itsmesinghavneet:gitlab123@github.com/itsmesinghavneet/baseline.git'
  #  - "curl -X POST -F token=a70ff62f6fb0f8013c687087ae5565 -F ref=test https://gitlab.com/api/v4/projects/7642571/trigger/pipeline"


