---
- hosts: localhost
  vars:
    - filename: '{{repo}}{{commit}}'
  tasks:
    - name: Write to file baseline_image
      lineinfile:
        path: '{{filename}}'
        create: yes
        state: touch
        line:  'maya 2b96ac cstor ac661b'
