apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: stage-test-openebs
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : stage-test-openebs
    spec:
      containers:
        - name: stage-test-openebs
          image: openebs/test-openebs-io:d03fe0
          imagePullPolicy: Always
          ports:
          - containerPort: 80